M48
; DRILL file {KiCad 7.0.1} date Fri Mar 24 14:03:17 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-24T14:03:17-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.0748Y1.5512
X4.0748Y-0.1654
X5.1378Y1.5512
X5.1378Y-0.1654
T0
M30
