M48
; DRILL file {KiCad (6.0.10)} date Fri Mar 24 14:32:09 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-24T14:32:09-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X4.0748Y1.5512
X4.0748Y-0.1654
X4.8031Y-0.1575
X5.1378Y1.5512
X5.1378Y-0.1654
T0
M30
